### ISSUE TITLE
how do you locate entity with multiple words?

### ISSUE THREAD

**Issue by ShellingFord221** [THU-BPM/MetaSRE#4]
Hi, in `train.py`, you find entity's position by:

```
# Find e1(id:2487) and e2(id:2475) position
pos1 = (encoded_dict['input_ids'] == 2487).nonzero()[0][1].item()
pos2 = (encoded_dict['input_ids'] == 2475).nonzero()[0][1].item()
e1_pos.append(pos1)
e2_pos.append(pos2)
```

What do 2487 and 2475 mean? If an entity is composed of multiple words (e.g. Gossip Girl), how do you get this entity's encoding? Thanks!

**Comment by ShellingFord221** [comment]
Are 2487 and 2475 just the IDs of symbol '<e1'> and '<e2'>?

**Comment by xuminghu** [comment]
As we pointed out in the paper, we use [E1] and [E2] to represent two entities, and 2487 and 2475 mean the IDs corresponding to [E1] and [E2] in the BERT Tokenizer.

**Comment by ShellingFord221** [comment]
So there is no vocabulary for entity's mention? Just the indicator [E1] and [E2] for entities in all sentences?

**Comment by xuminghu** [comment]
Yes, since BERT could encode contextualized relational features, [E1] and [E2] could be used to represent entity-level relational features. A similar approach can also be found in [our reference paper](https://www.aclweb.org/anthology/P19-1279.pdf) Figure 3.

**Comment by ShellingFord221** [comment]
Got it. Thx.
