### ISSUE TITLE
cannot achieve the performance reported in paper

### ISSUE THREAD

**Issue by ShellingFord221** [THU-BPM/MetaSRE#5]
Hi, I've tried your code on both SemEval and TACRED, but I found that MetaSRE cannot achieve the performance of TACRED reported in the paper, and the difference is quite big. TACRED is more skewed with 80% no_relation sentences, how do you handle this problem in training? Thanks!

**Comment by xuminghu** [comment]
Thanks for your interest to our work! During training, we did not perform any special processing on "no_relation". During the evaluation, we followed the [baseline](https://github.com/INK-USC/DualRE/blob/master/utils/scorer.py#L26) and ignored the predictions of "no relation" sentences.
